version: "3"
services:
  auth:
    build: ./auth-api
    platform: linux/arm64/v8
    ports:
      - '8000:3000'
    env_file:
      - ./env/auth.env
  users:
    build: ./users-api
    platform: linux/arm64/v8
    ports:
      - '8080:3000'
    env_file:
      - ./env/users.env
  tasks:
    build: ./tasks-api
    platform: linux/arm64/v8
    ports:
      - '3000:3000'
    env_file:
      - ./env/users.env